#!/bin/bash

TAG=skogsbaer/praktomat-checker-base:latest

if [ "$1" == "--help" ]; then
    echo "USAGE: $0 PLATFORM"
    echo "PLATFORM is either linux/arm64 or linux/amd64 (default)"
    exit 1
fi

if [ -z "$1"  ]; then
    platform="linux/amd64"
else
    platform="$1"
fi

cd $(dirname $0)
docker build --platform "$platform" --tag $TAG . || exit 1

echo
echo "Successfully build image with tag $TAG."

if [ $(hostname) == "progcheck" ]; then
    echo "Not pushing because we are running on progcheck"
elif [ "$platform" == "linux/arm64" ]; then
    echo "Not pushing image for ARM64"
else
    docker push $TAG
    echo "Successfully pushed image with tag $TAG"
fi
