#!/bin/bash

TAG=skogsbaer/praktomat-checker-base:latest

if [ -z "$1" ]; then
    echo "USAGE: $0 PLATFORM"
    exit 1
fi

cd $(dirname $0)
docker build --platform $1 --tag $TAG . || exit 1
docker push $TAG
