#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "USAGE: $0 --build-base PLATFORM"
    echo "Platform is either linux/arm64 or linux/amd64"
    exit 1
fi

if [ "$1" == "--build-base" ]; then
    shift
    echo $1
    echo "Building docker base image ..."
    $(dirname $0)/../../checker-container/docker-build "$1" || exit 1
    echo "Done building docker base image"
fi

if [ -z "$1" ]; then
    echo "No platform given, aborting"
    exit 1
fi

TAG=skogsbaer/praktomat-multi-checker:latest

cd $(dirname $0)
trap "rm -rf checker" EXIT
cp -r ../script/ checker
docker build --platform "$1" --tag $TAG . || exit 1
docker push $TAG
echo
echo "Successfully build and pushed image with tag $TAG"
