#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "USAGE: $0 --build-base"
    exit 1
fi

if [ "$1" == "--build-base" ]; then
    echo "Building docker base image ..."
    $(dirname $0)/../../checker-container/docker-build || exit 1
    echo "Done building docker base image"
fi

TAG=skogsbaer/praktomat-multi-checker:latest

cd $(dirname $0)
trap "rm -rf checker" EXIT
cp -r ../script/ checker
docker build --tag $TAG . || exit 1
docker push $TAG
echo
echo "Successfully build and pushed image with tag $TAG"
