#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "USAGE: $0 --build-base"
    exit 1
fi

if [ "$1" == "--build-base" ]; then
    echo "Building docker base image ..."
    $(dirname $0)/../../checker-container/docker-build || exit 1
    echo "Done building docker base image"
fi

TAG=skogsbaer/python-wypp-checker:latest

cd $(dirname $0)
trap "rm -f script.py" EXIT
cp ../scripts/check-python-wypp.py check.py
docker build --tag $TAG . || exit 1
docker push $TAG
